#!/bin/sh
cd /Users/vvtaranov/Projects/ponypod/ponypod-web
tmux has-session -t ponypod-web
if [ $? != 0 ]; then
  tmux new-session -s ponypod-web -n vim -d
  tmux send-keys -t ponypod-web 'vim' Enter
  tmux split-window -h -t ponypod-web
  tmux send-keys -t ponypod-web:vim.2 'git status' Enter
fi
tmux attach -t ponypod-web
