#!/bin/sh
cd /Users/vvtaranov/Projects/llamaInCoffeeShop/www
tmux has-session -t llama
if [ $? != 0 ]; then
  tmux new-session -s llama -n vim -d
  tmux send-keys -t llama 'vim' Enter
  tmux split-window -h -t llama
  tmux send-keys -t llama:vim.2 'cd ..' Enter
  tmux send-keys -t llama:vim.2 'git status' Enter
fi
tmux attach -t llama
